let num = "15"
console.log(num)
num = Number(num)
console.log(num)
console.log("Null: ", Boolean())
console.log("String: ", Boolean("Serhan"))
console.log("Positive: ", Boolean(1))
console.log("Zero: ", Boolean(0))
console.log("Negative: ", Boolean(-1))
console.log("Undefined: ", Boolean(undefined))
console.log("NaN: ", Boolean(NaN))